import { Bot, Menu, ShoppingCart, Sparkles } from "lucide-react";
import { Link, NavLink, Outlet, useNavigate } from "react-router-dom";
import { useState } from "react";
import { useShopper } from "../app/session-provider";
import { cn } from "../lib/utils";
import { AssistantComposer } from "../features/assistant/composer";

const categories = [{ label: "Fashion", key: "tshirts" }, { label: "Electronics", key: "laptops" }, { label: "Footwear", key: "sneakers" }, { label: "Bags", key: "backpacks" }, { label: "Wearables", key: "smartwatches" }];
export function MarketplaceLayout() { const { session } = useShopper(); const [open, setOpen] = useState(false); const navigate = useNavigate(); return <div className="min-h-screen pb-24"><header className="sticky top-0 z-40 bg-fk-blue text-white shadow-md"><div className="page-shell flex h-16 items-center gap-3"><Link to="/" className="shrink-0 leading-none"><span className="text-xl font-extrabold italic tracking-tight">Flipkart</span><span className="block text-[9px] font-medium text-fk-yellow">Explore <b>Plus</b></span></Link><div className="hidden flex-1 lg:block"><AssistantComposer compact onSent={() => navigate("/search")} /></div><nav className="ml-auto hidden items-center gap-1 md:flex"><NavLink to="/" className="rounded-md px-3 py-2 text-sm font-semibold hover:bg-white/10">Home</NavLink><NavLink to="/compare" className="rounded-md px-3 py-2 text-sm font-semibold hover:bg-white/10">Compare</NavLink><Link to="/cart" className="flex items-center gap-2 rounded-md px-3 py-2 text-sm font-semibold hover:bg-white/10"><ShoppingCart size={18}/><span>Cart</span>{session?.cart.item_count ? <b className="rounded-full bg-fk-yellow px-1.5 text-xs text-fk-ink">{session.cart.item_count}</b> : null}</Link></nav><button className="focus-ring rounded-md p-2 md:hidden" onClick={() => setOpen(!open)} aria-label="Toggle menu"><Menu /></button></div>{open && <div className="border-t border-white/15 px-4 py-3 md:hidden"><div className="page-shell"><AssistantComposer compact onSent={() => { setOpen(false); navigate("/search"); }} /></div></div>}</header><div className="border-b bg-white"><div className="page-shell flex gap-1 overflow-x-auto py-2">{categories.map((item) => <Link key={item.key} to={`/category/${item.key}`} className="whitespace-nowrap rounded-md px-3 py-1.5 text-sm font-medium text-slate-600 hover:bg-blue-50 hover:text-fk-blue">{item.label}</Link>)}<span className="ml-auto hidden items-center gap-1 text-xs text-slate-500 sm:flex"><Sparkles size={14} className="text-fk-blue"/> AI shopping, naturally</span></div></div><main><Outlet /></main><div className="fixed bottom-4 right-4 z-30 hidden lg:block"><Link to="/search" className={cn("focus-ring flex items-center gap-2 rounded-full bg-fk-blue px-4 py-3 text-sm font-bold text-white shadow-lift transition hover:-translate-y-0.5")}><Bot size={18}/> Ask the assistant</Link></div></div> }
