"""FastAPI app: create a session, send turns. No fixtures, live services only."""

from __future__ import annotations

import uuid

from fastapi import FastAPI, HTTPException, Response
from pydantic import BaseModel, Field

from . import memory, orchestrator
from .contracts import TurnRequest, TurnResult, TurnStatus
from .sarvam import SarvamError, default_client

app = FastAPI(title="fkgrid chat")


class CreateSessionResponse(BaseModel):
    session_id: str


class TurnBody(BaseModel):
    message: str = Field(min_length=1, max_length=2_000)


class SpeechSynthesisBody(BaseModel):
    """Text generated by a turn, plus the language detected for that turn."""

    text: str = Field(min_length=1, max_length=2_500)
    language_code: str = Field(default="en-IN", min_length=2, max_length=20)
    speaker: str | None = Field(default=None, min_length=1, max_length=40)


@app.get("/healthz")
def healthz() -> dict:
    return {"status": "ok"}


@app.post("/v1/sessions", response_model=CreateSessionResponse)
def create_session() -> CreateSessionResponse:
    session_id = uuid.uuid4().hex
    memory.create_session(session_id)
    return CreateSessionResponse(session_id=session_id)


@app.get("/v1/sessions/{session_id}")
def get_session(session_id: str):
    state = memory.get_session(session_id)
    if state is None:
        raise HTTPException(status_code=404, detail="SESSION_NOT_FOUND")
    return state


@app.post("/v1/sessions/{session_id}/turns", response_model=TurnResult)
def post_turn(session_id: str, body: TurnBody) -> TurnResult:
    if memory.get_session(session_id) is None:
        raise HTTPException(status_code=404, detail="SESSION_NOT_FOUND")
    request = TurnRequest(session_id=session_id, message=body.message)
    result = orchestrator.handle_turn(request)
    if result.status == TurnStatus.ERROR:
        raise HTTPException(
            status_code=502,
            detail={"message": result.message, "error_code": result.error_code},
        )
    return result


@app.post(
    "/v1/speech/synthesize",
    response_class=Response,
    tags=["speech"],
    summary="Synthesize generated assistant text in its response language",
)
@app.post(
    "/v1/speech/text-to-speech",
    response_class=Response,
    include_in_schema=False,
)
def synthesize_speech(body: SpeechSynthesisBody) -> Response:
    try:
        client = default_client()
    except ValueError as exc:
        raise HTTPException(status_code=503, detail=str(exc)) from exc
    if client is None:
        raise HTTPException(status_code=503, detail="SARVAM_API_KEY_REQUIRED")
    try:
        audio = client.synthesize(
            body.text,
            language_code=body.language_code,
            speaker=body.speaker,
        )
    except SarvamError as exc:
        status_code = 504 if "TIMEOUT" in exc.code else 502
        raise HTTPException(status_code=status_code, detail=exc.code) from exc
    return Response(
        content=audio.content,
        media_type=audio.content_type,
        headers={
            "Content-Disposition": "inline; filename=assistant-response.wav",
            "X-Sarvam-Language-Code": audio.language_code,
        },
    )
