import { GitCompareArrows, Heart, ShoppingCart, Star } from "lucide-react";
import { Link } from "react-router-dom";
import type { Entry } from "../../api/types";
import { useShopper } from "../../app/session-provider";
import { Button } from "../../components/ui";
import { display, inr } from "../../lib/utils";

const fact = (entry: Entry, label: string) => entry.facts.find((item) => item.label === label)?.typed_value;
export function ProductCard({ entry, browse = false }: { entry: Entry; browse?: boolean }) { const { compare, toggleCompare, send } = useShopper(); const price = fact(entry, "price") as { amount_paise?: number } | undefined; const rating = fact(entry, "rating"); const availability = String(fact(entry, "availability") ?? "UNKNOWN"); const chosen = compare.some((item) => item.result_entry_id === entry.result_entry_id); const add = () => send(undefined, "UPDATE_CART", { operations: [{ type: "ADD_ITEM", operation_id: crypto.randomUUID(), result_entry_id: entry.result_entry_id, quantity: 1 }] });
 return <article className="group surface relative overflow-hidden transition duration-200 hover:-translate-y-0.5 hover:shadow-lift"><Link to={`/product/${entry.result_entry_id}`} className="block"><div className="relative flex h-44 items-center justify-center bg-[#f7f9fc] p-5"><div className="absolute right-3 top-3 rounded-full bg-white p-2 text-slate-400 shadow-sm"><Heart size={16}/></div><div className="grid h-28 w-28 place-items-center rounded-2xl border border-white bg-gradient-to-br from-blue-100 to-slate-100 text-center text-xs font-bold leading-4 text-fk-blue">{display(fact(entry, "category"))}<br/><span className="text-slate-500">FK select</span></div></div><div className="p-4"><p className="line-clamp-2 min-h-10 text-sm font-semibold leading-5 text-fk-ink">{entry.title}</p><div className="mt-2 flex items-center gap-2"><span className="rounded bg-[#388e3c] px-1.5 py-0.5 text-xs font-bold text-white">{display(rating)} <Star className="inline" size={10} fill="currentColor"/></span><span className="text-xs text-slate-500">{display(fact(entry, "brand"))}</span></div><p className="mt-3 text-lg font-bold">{inr(price?.amount_paise)}</p><p className={`mt-1 text-xs font-semibold ${availability === "AVAILABLE" ? "text-[#388e3c]" : "text-amber-600"}`}>{availability === "AVAILABLE" ? "In stock" : display(availability)}</p></div></Link><div className="flex gap-2 border-t bg-white p-3"><Button variant="outline" className="h-9 flex-1 px-2" onClick={() => toggleCompare(entry)}><GitCompareArrows size={15}/>{chosen ? "Added" : "Compare"}</Button><Button className="h-9 flex-1 px-2" disabled={availability !== "AVAILABLE"} onClick={() => void add()}><ShoppingCart size={15}/>Add</Button></div>{browse && <div className="absolute left-3 top-3 rounded bg-white/95 px-2 py-1 text-[10px] font-bold text-slate-500">DEMO CATALOG</div>}</article> }
export function ProductGridSkeleton() { return <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{Array.from({ length: 6 }, (_, index) => <div className="surface overflow-hidden" key={index}><div className="h-44 animate-pulse bg-slate-100"/><div className="space-y-3 p-4"><div className="h-4 w-4/5 animate-pulse rounded bg-slate-200"/><div className="h-4 w-1/2 animate-pulse rounded bg-slate-200"/></div></div>)}</div> }
