import { Mic, Send, Sparkles } from "lucide-react";
import { useRef, useState } from "react";
import { useShopper } from "../../app/session-provider";
import { shopperApi } from "../../api/shopper";
import { Button } from "../../components/ui";

export function AssistantComposer({ compact = false, onSent }: { compact?: boolean; onSent?: () => void }) { const { send, session } = useShopper(); const [value, setValue] = useState(""); const [busy, setBusy] = useState(false); const [recording, setRecording] = useState(false); const recorder = useRef<MediaRecorder>(); const chunks = useRef<Blob[]>([]);
  async function submit() { if (!value.trim() || busy) return; setBusy(true); await send(value.trim()); setValue(""); setBusy(false); onSent?.(); }
  async function voice() { if (recording && recorder.current) { recorder.current.stop(); return; } try { const stream = await navigator.mediaDevices.getUserMedia({ audio: true }); const media = new MediaRecorder(stream); chunks.current = []; media.ondataavailable = (event) => chunks.current.push(event.data); media.onstop = async () => { setRecording(false); stream.getTracks().forEach((track) => track.stop()); try { const blob = new Blob(chunks.current, { type: media.mimeType }); const transcript = await shopperApi.speech(blob); setValue(transcript.text); } catch { /* The typed composer remains available. */ } }; recorder.current = media; media.start(); setRecording(true); } catch { /* Permission errors should not interrupt shopping. */ } }
  return <div className={compact ? "flex items-center rounded-lg bg-white p-1 shadow-sm" : "surface p-2"}><Sparkles className="ml-2 shrink-0 text-fk-blue" size={compact ? 17 : 20}/><input value={value} onChange={(event) => setValue(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter") void submit(); }} className="min-w-0 flex-1 bg-transparent px-2 text-sm text-fk-ink outline-none placeholder:text-slate-400" placeholder={compact ? "Search for products, compare, or ask AI..." : "Tell us what you're shopping for"} aria-label="Ask the shopping assistant"/><button type="button" disabled={!session?.model.speech_configured} onClick={() => void voice()} className={`focus-ring rounded-md p-2 ${recording ? "bg-red-50 text-red-600" : "text-slate-500 hover:bg-slate-100"}`} aria-label="Use voice input"><Mic size={18}/></button><Button type="button" onClick={() => void submit()} disabled={busy || !value.trim()} className="h-9 px-3" aria-label="Send request"><Send size={16}/><span className="hidden sm:inline">Ask</span></Button></div>;
}
